### ISSUE TITLE
Use declarative approach for defining movements of bower-retrieved resources

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#1]
As discussed here:
https://community.jboss.org/message/820037#820037

```
[
  { what: "components/font-awesome/build/assets/font-awesome/font/*", where: "fonts/fontawesome" },
  { what: "components/font-awesome/build/assets/font-awesome/less/*.less", where: "styles/fontawesome" },
  ...
]
```

**Comment by bleathem** [comment]
We should consider not moving the bower-retrieved resources.  We can reference them in the dev samples directly from the `components` tree.  This way we are not tempted into editing the files directly when an issue is found.

In general, bower-retrieved resources should not be copied to our dist either.  Rather we should focus on providing only our own resources via the dist mechanism.  I filed #5 to address what we include in our dist.

**Comment by lfryc** [comment]
Yes,

but at the end, we should provide a minified package of those resources.

**Comment by pauldijou** [comment]
Okay, after a bit of talking, I think we all agree we don't really need to copy Bower resources anymore. One of the goal was to abstract from other project layouts but it isn't really worth it. We will now reference directly required resources from the `component` folder and, if needed, Grunt will be able to process/concat/minify them.

**Comment by pauldijou** [comment]
What about resources not present in Bower? Bootstra 3.0 isn't reference in Bower right now.

**Comment by lfryc** [comment]
Afaik Bower can reference plain Git references as well:

See Installing packages and dependencies from http://bower.io/.
