### ISSUE TITLE
pickList: order of buttons in the stack is not user friendly

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#105]
Could you please consider the order of the buttons in the stack of a `pickList` ?

IMHO the current order: remove all, remove, add, add all is not user friendly. 
When working with the `pickList`, there are more common `add` and `addAll` operation IMHO.

I am not sure whether it is my legacy problem, that I am used to use different order, but anyway I think that the older one is more appropriate.

I would appreciate more the old one: add, add all, remove, remove all - as it is in RF3 and RF4.

Old order of buttons from RF4 and RF3
![rf4picklistbuttonsorder](https://f.cloud.github.com/assets/825261/1481663/38e23ca4-46ce-11e3-8412-3985f5ee27a6.png)

RW order
![rwbuttonsorder](https://f.cloud.github.com/assets/825261/1481666/404cab28-46ce-11e3-89f4-866f6a3c2f28.png)

**Comment by jhuska** [comment]
I am actually wondering whether we can not change this to feature request.

To enable a user to define the order according to his needs. Is it feasible ? IMHO the API can be similar to how user can set text to the buttons.

E.g.
`var options = { buttonsOrder: {add: 0, addAll: 1, remove: 2, removeAll: 3} }`
`$('#myDiv').widgetName(options);`

**Comment by bleathem** [comment]
We could, but let's let a user (with a corresponding use case) request it.
