### ISSUE TITLE
orderingList: fix all dangerous public api functions

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#115]
check all public api methods for similar reason as in #111 (function can interact with not contained elements)

**Comment by bleathem** [comment]
Resolved with ea8d659

**Comment by jstefek** [comment]
@bleathem what about these: `isSelected` , `selectItem` and `unSelectItem`. Shouldn't they also check if it contains such elements?

Reasons:
- this is dangerous: `$('#list').orderingList('selectItem', $('*'));`
- provided documentation of the methods, e.g. `unSelectItem: @param item {Object} jQuery object of the orderingList element to un-select`

**Comment by bleathem** [comment]
Thanks @jstefek.  0.1 is already release, would you please file a new issue we can track for the next release?
