### ISSUE TITLE
pickList: change event is triggered even when there is no change in target list state

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#118]
Change event doc for `pickList` says:
_Fired when the target list of the pickList changes values._

However, the `change` event is triggered also when the state of the target list is not changed.

Steps to reproduce:
1. load `pickList` demo, register change callback beforehand
2. click on the `addAll` button
3. see that change callback is invoked
4. click again on `addAll` button
5. see that the change callback is again invoked, even when there was no change in the target list

**Comment by jhuska** [comment]
I would say that it is rather `orderingList` issue. Am I right ?

In this line https://github.com/richwidgets/richwidgets/blob/master/src/widgets/select/ordering-list.js#L503
,the `change` event is triggered when `add` function on `orderingList` is called independently on whether some items were actually added.

**Comment by bleathem** [comment]
+1.  The add_/remove_ methods should return immediately if passed a list of empty elements
