### ISSUE TITLE
chart: _destroy method name should not start with underscore as it is in public API

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#119]
If I understand things correctly the method:
`_destroy`
of chart component, should be renamed to:
`destroy`
as it is in the public API of the widget.

**Comment by bleathem** [comment]
Rather the converse.  The jQuery Widget factory invokes the widget's _destroy method:

See: https://github.com/jquery/jquery-ui/blob/master/ui/jquery.ui.widget.js#L276

We've updated the contributing guide stating that all widgets should implement the _destroy mehod.  We'll have to add some empty YUIdoc to get the method included in the generated doc.

http://www.richwidgets.io/contributing.html (see lifecycle methods)
