### ISSUE TITLE
Enable JSLint and other quality tools to preserve consistency

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#12]
JSLint should be enabled to preserve in form of Grunt task to preserve consistency of:
- line indentation
- code formatting
- common mistakes
- string literals (quote marks)

**Comment by bleathem** [comment]
I enabled jshint, and fixed the warnings in _src/widgets_ and in _tests_.  I also fixed the warnings in _src/demos_ except for ones with the undefined _source_ argument in the autocomplete demos.

@lfryc can you run `grunt jshint:demos` and resolve the warnings that come up?  Once that is complete we can resolve this issue.

**Comment by bleathem** [comment]
@lfryc I figured out what you were doing with the _source_ global in your autocomplete demos.  I worked past the jshint errors by adding source to the list of allowed globals, but we should really re-visit how we are approaching this.  

I think we could take advantage of handlebar templating to get rid of the global, and make the demo more clear.

**Comment by lfryc** [comment]
@bleathem definitely, let's create an issue.
