### ISSUE TITLE
pickList: when not orderable and has more items than viewport, selecting of item is broken (on Chrome)

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#123]
This issue relates to the `orderingList` one:
https://github.com/richwidgets/richwidgets/issues/122

The same issue can be reproduced on `pickList`, however, there is another slightly different issue:

_When `pickList` is not `orderable`, and there is more items than the viewport, than selecting of an item causes that: two items are selected, the original one which was clicked on and also another one below (caused by the viewport scrolling issue with ordering list referenced above)._

It is noticeable only on Chrome, Firefox works.

Steps to reproduce:
1. checkout this branch https://github.com/jhuska/richwidgets/tree/moreItems
2. build the demo and load page for `pickList`
3. click on the item, e.g. 5th from the bottom
4. see that two items are selected: the correct one and also one shifted down

**Comment by bleathem** [comment]
This is caused by setting the tabIndex of the `.ordering-list` div.  Removing this attribute resolves the problem.  

However, the tabindex is present to allow the div to respond to focus events.  Removing the tabindex altogether will break focus and blur listeners.

**Comment by bleathem** [comment]
This YUI issue has a good description of the problem: https://github.com/yui/yui3/issues/728

**Comment by bleathem** [comment]
This stackoverflow question has a possible solution:
http://stackoverflow.com/questions/14979365/table-scroll-bar-jumps-up-when-table-receives-focus-in-ie

``` javascript
$('#wrapper').scroll(function(){
    $(this).data( {posY: $(this).scrollTop()} )
})
.blur(function(){
    $(this).scrollTop( $(this).data("posY") );
})
```

**Comment by bleathem** [comment]
Here's a fix more applicalbe to our situation:

``` javascript
$('.ordering-list')
          .focus(function(){
            var x = window.scrollX, y = window.scrollY;
            setTimeout(function() {
              window.scrollTo(x,y);
            }, 0)
          })
```
