### ISSUE TITLE
orderingList: when a single class is provided to @columnClasses, only first column has this class

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#124]
- open http://www.richwidgets.io/select/ordering-list.html
- run in console: `$('#table').orderingList({columnClasses: 'singleClass'});`
- expected: every column contains class `singleClass`
- have: only the first column has this class (it can be even a handle when `dragSelect` is true)

Please, also check states, when there are more columnClasses than columns.

**Comment by bleathem** [comment]
This was done intentionally, mimicing what is done in JSF:
https://javaserverfaces.java.net/nonav/docs/2.1/vdldocs/facelets/h/dataTable.html

> Comma-delimited list of CSS style classes that will be applied to the columns of this table. A space separated list of classes may also be specified for any individual column. If the number of elements in this list is less than the number of actual column children of the UIData, no "class" attribute is output for each column greater than the number of elements in the list. If the number of elements in the list is greater than the number of actual column children of the UIData, the elements at the posisiton in the list after the last column are ignored.

**Comment by jstefek** [comment]
OK then, thanks for clarification.
