### ISSUE TITLE
Automate Grunt distribution build and Karma testing using Travis

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#13]

**Comment by lfryc** [comment]
Karma is not currently part of Grunt dist build.

**Comment by bleathem** [comment]
@lfryc I setup dist to invoke the karma tests.  Do you want to proceed with the travis setup?

**Comment by lfryc** [comment]
Yea, I can do it.

**Comment by lfryc** [comment]
Actually, automation is addressed in scope of #4, so closing this one.

Thanks for covering that!
