### ISSUE TITLE
pickList: custom pickList buttons text breaks the layout of buttons

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#130]
If you set for example this to `pickButtonsText` option of `pickList`:
`{addAll: 'add all', add: 'add', remove: 'remove', removeAll: 'remove all'}`

Then the rendered `pickList` has a slightly broken layout of the buttons.

Please see this screenshot. The buttons **are not centered**.
![badresponzivenesscustombuttons](https://f.cloud.github.com/assets/825261/1522221/7cd7d15a-4ba4-11e3-8f8e-37ccf832f144.png)

It is even more broken when **decreasing** the **browser window size**. Then buttons **overlaps** the target list.
![badresponzivenesssmallerwindow](https://f.cloud.github.com/assets/825261/1522232/9f0aa13a-4ba4-11e3-8268-80c8d1d84729.png)

Is this a bug towards `pickList` **responsive** design ?

**Comment by bleathem** [comment]
This is unfortunate, and is attributable to the use of the Bootstrap grid for laying out the panels.  The widget will have to be re-factored using custom CSS for layout.

In the meantime, a workaround is the following CSS:

``` CSS
middle {
    width: 16%;
}
.target-wrapper {
    width: 42%;
}
```
