### ISSUE TITLE
Autocomplete problems

### ISSUE THREAD

**Issue by pauldijou** [richwidgets/richwidgets#14]
- [x] If I click on the arrow button without any focus on the input, it will open the dropdown. But then, if I click outside or escape key, it will no close it.
- [x] If the dropdown has many elements and overflow outside of the screen, it will force to scroll over the whole window. IMO, the scroll should be inside the dropdown itself. To make it easier, we can think of a max-height as an option of the autocomplete.

-> https://github.com/richwidgets/richwidgets/issues/40
- [x] Also, if the autocomplete is really near the bottom of the screen, it would be awesome that the dropdown actually appears on top of it.

-> https://github.com/richwidgets/richwidgets/issues/42
- [x] Small detail, but maybe it would be better to remove the border-radius at the top of the dropdown...

**Comment by lfryc** [comment]
"Small detail, but maybe it would be better to remove the border-radius at the top of the dropdown..." - it would make sense if input would change the bottom-edge styling as well.

I think this is up to end user to customize styling if necessary.

**Comment by lfryc** [comment]
All the issues were covered either by creating enhancement requests or I verified that they are no longer an issue.
