### ISSUE TITLE
select2: images aren't referenced correctly

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#183]
We need to make relative links from external sources (such as select2.css) work both in development and production modes.

**Comment by lfryc** [comment]
PR fixes the issue: https://github.com/richwidgets/richwidgets/pull/184

@bleathem would you mind to review it?

**Comment by lfryc** [comment]
Because it is not so obvious, I will describe what I have done here:
- `dist/assets` are _copied_ to `dist/demos/assets`
  - because we need to reference resources from demo
- `dist/demos/demo-assets` were _moved_ to `dist/demos/assets/demo`
  - because `richwidgets-demo.min.css` needs to be on same level as `richwidgets.min.css`

The another trick hidden there is our `src/widgets/input/select.less` referencing `lib/select2/select2.css` file but [treating it as less](http://lesscss.org/features/#import-options) - this way 
- the `select2.css` is processed as LESS (even though no special LESS instructions are used)
- and url(*) are rewritten by `assemble-less`
- and the configuration for `rootpath` and `relativeUrls` is applied

This all fixes links and works in dev and production modes.

**Comment by bleathem** [comment]
Clever Lukas.  This fix will undoubtedly pay dividends as we incorporate additional libraries.
