### ISSUE TITLE
gitignore /dist

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#2]
The /dist folder should be built using grunt instead and as a result of build process, it should not be placed in VCS:

https://github.com/richfaces/richfaces-widgets/tree/b8af4925e6c8dd4678987cc1fe8483e39ae55d08/dist

**Comment by bleathem** [comment]
The only benefit of placing the dist in source control is that folks can grab and use our resources without having to setup the build environment.

If we remove the dist from source control, we should investigate hosting our generated resources somewhere.  Perhaps using the github _pages_ service.  I think that's how bootstrap does it.

**Comment by pauldijou** [comment]
I agree that it should be on the `.gitignore` file. I didn't put it for now for the reason described by @bleathem but you're right, it would be better to be clean about that. The moment we find a place to host the compiled files, we can remove it for good.

**Comment by lfryc** [comment]
Second option would be linking to original resources in dev mode and
creating distribution later, as we have discussed (on a sample of
yeoman-angular boilerplate) - that way you won't need any compilation step.
