### ISSUE TITLE
Run tests in multiple browsers

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#28]
Currently the richwidget test suite can be run in Chrome and PhantomJS.  We should run the tests in all our supported browsers.
- [x] Add necessary configuration to run tests locally in Firefox
- [x] Set up the [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher) plugin to run the tests in sauce-labs

**Comment by ppitonak** [comment]
@bleathem, what do you mean by "Add necessary configuration to run tests locally in Firefox"? I can run tests locally in Firefox (although some fail)

**Comment by bleathem** [comment]
Yep, tests run (and fail) in Firefox locally for me too.  Whatever issue I was having must have been resolved with recent karma/jasmine upgrade on our part.

**Comment by lfryc** [comment]
We can configure continuous integration on CloudBees - matrix job (similar to [1]) including each supported browsers, with [junit reporter](https://github.com/karma-runner/karma-junit-reporter) enabled and [hook for building pull requests](https://wiki.cloudbees.com/bin/view/DEV/Github+Pull+Request+Validation).

Let me know if you have sufficient priviliges to access CloudBees and SauceLabs accounts for RichFaces project.

[1] https://arquillian.ci.cloudbees.com/job/arquillian-graphene-webdriver-ftest-browsers/

**Comment by ppitonak** [comment]
I sent a pull request with Sauce Labs configuration.

There are multiple browsers configured: Chrome latest, Firefox ESR, Firefox latest, IE8, IE9, IE10, IE11 (preview), Safari latest, Opera latest, iPhone, and Android.

However, the test suite doesn't finish in IE8, IE9 and iPhone. I will investigate more later.

To run on Sauce Labs, one needs to set his environment variables SAUCE_USERNAME and SAUCE_ACCESS_KEY and start Karma with the list of desired browsers, e.g. this will launch both locally installed Firefox and one on Sauce Labs:

```
karma start --browsers=Firefox,SL_Firefox_latest
```

Be aware of the fact that running tests in the cloud is much slower than running locally. These are results for the command above:

Firefox 25.0.0 (Linux): Executed 65 of 65 (17 FAILED) (23.164 secs / 22.574 secs)
Firefox 24.0.0 (Windows XP): Executed 65 of 65 (17 FAILED) (1 min 3.218 secs / 56.267 secs)

**Comment by lfryc** [comment]
I have spitted a specific issue for continous integration concerns:
https://github.com/richwidgets/richwidgets/issues/95

**Comment by lfryc** [comment]
Works great, thanks @ppitonak .

Tests are obviously slower, but for continuous integration purposes that's enough.

Good job.
