### ISSUE TITLE
Widget API review

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#29]
Review the API of all widgets, checking for consistency

**Comment by bleathem** [comment]
Autocomplete cache implementation/instantitation should be revisitied

**Comment by bleathem** [comment]
Comment in contributing guide on grouping and order of methods

**Comment by lmacko** [comment]
Chart widget API:
- already implemented
  - `resetZoom()`
  - `getPlotObject()`
- might be added
  -  `highlight(series,datapoint)` graphically highlight a point in a chart, same effect as mouseover
  -  `unhighlight()` clear highlighted points
  -  `zoomTo(xmin,ymin,xmax,ymax)` zoom to a specific part of  the chart
  -  `stacking(enabled)` http://www.flotcharts.org/flot/examples/stacking/index.html
  -  `showSeries(shown)` http://www.flotcharts.org/flot/examples/series-toggle/index.html

**Comment by bleathem** [comment]
:+1: those sound like good additions.

Anything that is on the "configuration" side of things though should be exposed as an initialisation option that can be mutated by the jQuery UI widget factory "option" method.  eg:

```
$("#myChart").chart("option", "stacking", true)
```

This may or may not apply for your specific proposals, it's hard to say without knowing the details of what the methods do.

**Comment by lfryc** [comment]
@bleathem I have reviewed pickList and orderingList and found one another issue:

```
_setOption: function(key, value) {
   $.Widget.prototype._setOption.apply(widget, arguments);
}
```

https://github.com/richwidgets/richwidgets/blob/master/src/widgets/select/ordering-list.js#L571

---

jQuery UI prefers to use `this._super(key, value)` or `this._superApply(arguments)` parent delegation:

https://github.com/richwidgets/richwidgets/blob/master/src/widgets/input/autocomplete.js#L400

I consider it more clean as well.

I have refactored these widgets and noted this in conventions.
