### ISSUE TITLE
Whitespace differences in style attributes cause test failure

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#31]
The picklist-source test currently fails with the error:

```
    Report:
    =======
    BODY/DIV[1]/DIV[@id='table']/DIV[1]/DIV[1]/DIV[1]/DIV/TABLE/TBODY/TR[9]
        Attribute 'style': expected value 'height: 0px; display: none;' instead of 'height: 0px; display: none; 'BODY/DIV[1]/DIV[@id='table']/DIV[7]/DIV[1]/DIV[1]/DIV[1]/TABLE/TBODY/TR[2]
        Attribute 'style': expected value 'height: 88px; display: table-row;' instead of 'height: 88px; display: table-row; '
```

Note the expected trailing space at the end of the style attribute.  Correcting for this in the fixture causes the test to pass in PhantomJS, but fail in Chrome. 

dom-compare has the option _stripSpaces_, but it does not work, an issue that may have been addressed upstream:
https://github.com/Olegas/dom-compare/issues/5

@lfryc : 
1. Have you tried opening an upstream Pull Request with your require.js changes so we don't have to depend on your fork?
2. If we must depend on a fork, we need to:
   1. Update the fork with the latest changes
   2. Move the fork into the richwidgets project

**Comment by lfryc** [comment]
I guess we would need to further refactor my solution - dom-compare uses CommonJS and we use RequireJS.

I would suggest to use UMD which covers all usual loaders:
https://github.com/umdjs/umd

**Comment by lfryc** [comment]
Opened upstream issue, prepared to issue a pull request after discussion:
https://github.com/Olegas/dom-compare/issues/6

**Comment by lfryc** [comment]
Created issue to address incorporation into upstream:
https://github.com/richwidgets/richwidgets/issues/49

**Comment by lfryc** [comment]
Please update your for `lib/dom-compare` by removing it and running `grunt bower` again in order to update a `requirejs` branch of `dom-compare`.
