### ISSUE TITLE
Align Autocomplete and its example with BS 3.0.0

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#38]
- [x] add form-controls class to all inputs in demo
- [x] set fixed width for all inputs in demo (it will inherit 100% otherwise)
- [x] button is generated outside of input - BS3 final must have another way to define the button for input

**Comment by bleathem** [comment]
> set fixed width for all inputs in demo

Be sure to keep the demo responsive.  Perhaps a bootstrap grid to size the inputs?

**Comment by lfryc** [comment]
Right, I used <div class="col-lg-6"> instead of "fixed width"
