### ISSUE TITLE
Charts demo is not responsive

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#39]
The charts demo uses a fixed width to size the charts.  This is not a responsive design, and leads to charts that spill off the screen on mobile devices.

**Comment by lfryc** [comment]
I think this is even broader issue - we need to allow charts to respond to resizing (inhedit a width, but also react to resize) since canvas IMHO doesn't respond to resizing automatically.

**Comment by bleathem** [comment]
We can register a window resize listener, triggering a chart regeneration when the window changes size.

**Comment by lmacko** [comment]
The updated chart demo uses responsive width now.
