### ISSUE TITLE
Publish API documentation for the widgets

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#56]
Some possibilities exist for parsing the javascript source a la "javadoc":
- https://github.com/jsdoc3/jsdoc (requires java)
- http://yui.github.io/yuidoc/ (runs on node.js)

While both have grunt plugins available, of the 2 yuidoc seems like a better fit.  Sample yuidoc API docs look like:
http://yui.github.io/yuidoc/api/

A Bootstrap 2 theme is available for yuidoc:
https://github.com/kevinlacotaco/yuidoc-bootstrap-theme/

**Comment by lfryc** [comment]
+1 for give a YUIDoc try

**Comment by bleathem** [comment]
A handy reference for YUI doc syntax:
http://yui.github.io/yuidoc/syntax/

**Comment by bleathem** [comment]
YUI doc added to our grunt build, using the Bootstrap 2 theme:
http://richwidgets.github.io/api/
