### ISSUE TITLE
Chart demos need a max-width

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#58]
The charts are now responsive, yay!  Unfortunately on a wide display the charts stretch out an unreasonable amount.

We can either implement a max-width option with the chart widgets, or we can try the simpler approach of nesting them in a div with a max-width css style rule set.

**Comment by lmacko** [comment]
I've set max-width css style rule to parent charts div. The demo is not updated because I don't have rights to commit richwidgets.github.io

**Comment by bleathem** [comment]
Thanks guys!
