### ISSUE TITLE
Clean up the Bower devDependencies

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#59]
All dependencies listed in the bower "dependencies" section are brought in transitively to child projects.  This is redundant as we ship many of our dependencies as part of our dist.

We should clean up the transitive despendencies, moving the non-required ones to deDependencies

**Comment by lfryc** [comment]
@bleathem could you please review the associated PR?

**Comment by bleathem** [comment]
The associated PR is #97
