### ISSUE TITLE
Chart demos are re-sized slightly too big

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#61]
The chart widgets demo is nicely responsive and responds to the max-width of the parent container.  however as I shrink the size of the window, some of the charts are resized slightly too large and hang off the side of the screen.

This may be caused by the margin/padding settings of the Bootstrap grid.  I had to account for that with the picklist too.  When resolving this, be sure the charts still size well when not in a Bootstrap grid (eg. by creating .container .chart-\* rules as required).

**Comment by lmacko** [comment]
Fixed. There was missing a flot plugin in minified resource. Online demo updated, also.

**Comment by bleathem** [comment]
This looks excellent, nice work Lukas!
