### ISSUE TITLE
Document the required version of npm required to build RichWidgets

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#64]
When running the `grunt` as the final command of building the RW repository, I am getting following error:

`No provider for "framework:jasmine"!`

I had to run it with --force to complete it.

**Comment by bleathem** [comment]
@jhuska what version of node are you using?  Make sure you are using node >= v0.10.15.

**Comment by jhuska** [comment]
@bleathem you are right. It was caused by old node version. 

I am wondering whether we can drop somewhere in the README.md info about minimal node version ? Also a hint to install it via nvm.

**Comment by bleathem** [comment]
+1 -- @jhuska can you investigate (through a binary search trial and error) what is the minimum version of `node` required to build RichWidgets?  We have too many deps to determine with a search through the upstream docs.  We can then include that in the README as appropriate.

---

Note: I spent some time to get the `engineStrict` flag to work in `package.json`, however apparently that is not a solution for us in this case, as:

> engineStrict works on a per-module basis; it has to be set in the package.json of a module you are installing
> [...] 
> engineStrict doesn't prevent you from installing dependencies if it's set in the package.json of the CWD.

**Comment by jhuska** [comment]
According to my last findings, the last version of node which works for me is:
_0.10.22_

Lower versions do not work in my environment: Fedora 19_x64

**Comment by lfryc** [comment]
Thanks for investigations, Juraj. I have documented recommended use of Node 0.10.22.
