### ISSUE TITLE
orderingList: @heightMin, @heightMax need to contain a unit

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#75]
The @height can be set without unit (px, em) and a default unit is inserted (px).

But these two attributes need to contain a unit. Shouldn't the widget also handle/insert missing unit for these two?
Or should this be just mentioned in docs?

**Comment by bleathem** [comment]
I'll have to play with it a bit and see.

**Comment by lfryc** [comment]
@jstefek , I can see that `heightMin` / `heightMax` are changing `min-height` / `max-height` values on `.scroll-box` element as expected (the same as `height` option does). `px` units are added to the provided values when number is provided as an option (the same as `height` option does).

Did I just misunderstood your report?

**Comment by jstefek** [comment]
@lfryc yes, it works perfectly with number as an option. 
I put there string parameters before, my bad.

So the question is: should or shouldn't it also work with string parameters?

**Comment by lfryc** [comment]
You are right,
- `height` works fine: `$('.scroll-box:has(#list)').css('height', 500);`
- but `min-height` doesn't: `$('.scroll-box:has(#list)').css('min-height', 500);`

I would say this is a bug in jQuery.

---

We should try latest jQuery and see whether the bug is still present,
and file a bug report if it is.

---

workaround:

```
height = /^[0-9]+$/.test(height) ? parseInt(height) : height;
```

**Comment by bleathem** [comment]
Further expanding on what works/doesn't work:
1. String Argument w/units
   
   :heavy_check_mark:: `$('.scroll-box:has(#list)').css('height', '500px');`
   :heavy_check_mark:: `$('.scroll-box:has(#list)').css('min-height', '500px');`
2. Numeric Argument
   
   :heavy_check_mark:: `$('.scroll-box:has(#list)').css('height', 500);`
   :heavy_check_mark:: `$('.scroll-box:has(#list)').css('min-height', 500);`
3. String Argument w/o units
   
   :heavy_check_mark:: `$('.scroll-box:has(#list)').css('height', '500');`
   :x:: `$('.scroll-box:has(#list)').css('min-height', '500');`

According to the jQuery [height docs](http://api.jquery.com/height/):

> When calling .height(value), the value can be either a string (number and unit) or a number. If only a number is provided for the value, jQuery assumes a pixel unit. **If a string is provided, however, a valid CSS measurement must be provided** for the height (such as 100px, 50%, or auto).

The fact that 3 works for height with a String parameter and no units is a bug.  We should verify that this is true with the latest version of jQuery and file an upstream bug.

IMO we don't need to do anything to resolve this issue, specifying units for CSS values is standard practice.
