### ISSUE TITLE
How to calll public API & private of widget - update docs

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#76]
The syntax for calling public or private methods of a widget is non-trivial, therefore it should be documented somewhere.

IMHO README.md contains quite general (getting started) info, but it is up to you.

The syntax is as follows:
- `$('#myDiv').pickList('method','param1','param2'...)` - prefered way for invoking public API methods
- `element.pickList(); var widget = element.data('pickList'); widget._dumpState().pickedKeys`

**Comment by bleathem** [comment]
We could create a USAGE.md file with this, and other RichWidget usage details.
