### ISSUE TITLE
Prepare RichWidgets for release

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#78]
We have worked out a reasonable `dist` structure for our upcoming release, however there are a few release-related issues that have as yet to be addressed.
- [x] Work out how we will include the assets in the [git release](https://help.github.com/articles/creating-releases).  
  
  Will we attach a zip of the dist?  Where will we draft/store the release notes?
- [x] Bower does not currently work with github releases
  
  see this rejected issue:
  
  > https://github.com/bower/bower/issues/584.
  
  We will have to include our dist folder in a repo/branch.  Git `subtree` may help us here, see this article for details:
  
  > https://github.com/yeoman/yeoman/wiki/Deployment
- [x] Define and register a RichWidgets package the bower repository
  
  > https://github.com/bower/bower#configuration
- [x] Draft a release-process asciidoc file

**Comment by lfryc** [comment]
I will investigate more what are our options.

**Comment by lfryc** [comment]
+1 Zip distribution - release notes can be added as a description (or even they might are available automatically on Milestones page)

**Comment by bleathem** [comment]
The git releases article describes how to manage release notes

**Comment by lfryc** [comment]
_Ad Bower_

We have agreed on [team meeting]() that we will use CI to build a `dist` branch which one can use in Bower.
- The `dist` branch will contain release tags.
- The `dist` branch will be updated as a post-commit hook (Web Hook) using continuous integration.

**Comment by lfryc** [comment]
I will prototype it on a custom RichWidgets  fork.

**Comment by lfryc** [comment]
Distribution generated automatically to https://github.com/richwidgets/richwidgets/commits/dist branch.

@bleathem can we register `richwidgets` package in bower repository now?

**Comment by bleathem** [comment]
@lfryc +1

Let's also change the RichFaces build to use this dist build, rather than the convoluted (and time consuming) process of building the bower dependency.

**Comment by bleathem** [comment]
I made the change to RichFaces with this commit:
https://github.com/richfaces/richfaces/commit/4745212044f2059d43e6d1ea694a04e93caf9e03

We can update it to use the bower dependency directly once RichWidgets is present in the bower registry.

**Comment by lfryc** [comment]
@bleathem anything else needed to resolve this issue?

**Comment by bleathem** [comment]
There is the final outstanding task in the issue description:

> Draft a release-process asciidoc file

**Comment by lfryc** [comment]
@bleathem , I have drafted a release process - would you mind to review it and review my comments?

https://gist.github.com/lfryc/7625055

**Comment by lfryc** [comment]
@bleathem : I have incorporated your suggestions, would you mind to give it final shot?

**Comment by lfryc** [comment]
The gist was updated according to the comments. @bleathem  note that [I don't get notifications](https://gist.github.com/maxogden/3422419) for gist changes.

**Comment by lfryc** [comment]
Ouch, closed accidentaly.

**Comment by lfryc** [comment]
A release process doc drafted here:
https://github.com/richwidgets/richwidgets/blob/master/release-process.adoc
