### ISSUE TITLE
orderingList: cannot init widget with functionality @mouseOrderable

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#81]
- open http://www.richwidgets.io/select/orderingList.html
- run in console 

```
$('#list').orderingList({mouseOrderable: false});
```
- the first list should not be mouse orderable, but it is

**Comment by jstefek** [comment]
But if you destroy it before, it works, but cannot be destroyed after that.

So if you run this: 

```
$('#list').orderingList('destroy').orderingList({mouseOrderable: false}).orderingList('destroy');
```

you'll get an error: 

```
Error: cannot call methods on sortable prior to initialization; attempted to call method 'destroy'
```

**Comment by bleathem** [comment]
If mouseOrderable is false, then the sortable plugin is not uesed.  Hence the error in destroying it.  We'll have to check if the sortable plugin is active before trying to disable it.

**Comment by bleathem** [comment]
Note:, in your steps to reproduce:
1. open http://www.richwidgets.io/select/orderingList.html
2. run in console $('#list').orderingList({mouseOrderable: false});

Step 2 is problematic, as the orderingList is already initialized (on page load) for the `#list` div.

Running destroy prior to re-initialization is the correct pattern.  So your stpes to reproduce should be:
1. open http://www.richwidgets.io/select/orderingList.html
2. run in console $('#list').orderingList('destroy');
3. run in console $('#list').orderingList({mouseOrderable: false});

(or chain the calls as you did in your comment.)

I'm leaving this issue open to address the error during the destroy call.  Also, this option should be mutable, so I'll check/impl that.
