### ISSUE TITLE
orderingList: cannot init widget with functionality @contained

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#82]
- open http://www.richwidgets.io/select/orderingList.html
- run in console 

```
$('#list').orderingList({contained: false});
```
- list item should be draggable outside of the list

But if you destroy it before, it works. 

```
$('#list').orderingList('destroy').orderingList({contained: false});
```

**Comment by bleathem** [comment]
I must have missed that option in the `_setOption` method.  Nice catch.

**Comment by lfryc** [comment]
This is duplicate of https://github.com/richwidgets/richwidgets/issues/80 as call of `$('#list').orderingList({contained: false});` effectively leads to calling `_setOption('contained', false);`.
