### ISSUE TITLE
pickList: mark event parameter as optional in addItems/removeItems methods

### ISSUE THREAD

**Issue by jhuska** [richwidgets/richwidgets#89]
**PickList** Public API methods `addItems` and `removeItems` require an `event` parameter to be passed alongside with the `items` to be added/removed.

According to the IRC discussion with @lfryc, `event` should be made optional parameter, as the user of this method probably does not need that parameter.

**Comment by lfryc** [comment]
As Brian explained on IRC, the `event` should be just marked `@optional` in docs.
