### ISSUE TITLE
pickList: table layout: when @height is set the fill item is wrongly counted

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#92]
As a result of this a scrollbar is rendered.

Works wrong in both FF and Chrome.
- open http://www.richwidgets.io/select/pick-list.html if firefox
- run in console

```
$('#table').pickList({height: 400});
```
- drag item from target list to source list (table layout example)
- expected: no scrollbar is present on empty target list

**Comment by bleathem** [comment]
The fill elements are calculating their size incorrectly.
