### ISSUE TITLE
Setup browsser-compatibility continuous integration jobs

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#95]
We can configure continuous integration on CloudBees - matrix job (similar to [1]) including each supported browsers, with junit reporter enabled and hook for building pull requests.

Let me know if you have sufficient priviliges to access CloudBees and SauceLabs accounts for RichFaces project.

[1] https://arquillian.ci.cloudbees.com/job/arquillian-graphene-webdriver-ftest-browsers/

Originally discussed here:
https://github.com/richwidgets/richwidgets/issues/28#issuecomment-27756332

**Comment by ppitonak** [comment]
I created a matrix job for several browsers on CloudBees [1]. However, it doesn't build pull requests yet, only master branch. I'll update it later.

[1] https://richfaces.ci.cloudbees.com/job/richwidgets-browser-matrix

**Comment by bleathem** [comment]
@ppitonak shall we close this issue and open a new one to track the pull-request configuration?
